### ISSUE TITLE
Problem Fold Operations

### ISSUE THREAD

**Issue by ThePhantom00** [PhosCity/Aegisub-Scripts#9]
Hi!
When i try to specify the fold marker, it creates a multiple marker of it like in the video

https://github.com/PhosCity/Aegisub-Scripts/assets/42273394/2348c50c-fddf-49dc-8f5e-2e9917cac340

sometimes it happens if i have old folds before the new update

**Comment by PhosCity** [comment]
The number of `>` is supposed to be the number of nested folds. So if you have a fold inside a fold, it'll have two `>`.  It works correctly for me so is it possible for you to provide the subtitle file you used in the video?

**Comment by PhosCity** [comment]
![image](https://github.com/PhosCity/Aegisub-Scripts/assets/65547311/30878034-ba61-47b6-96ba-72fddae902be)

I've made fold markers optional for now so you can just untick the box beside `Fold Marker` and it will not be added to line. However if you can, I'd still like the file to check why this issue occured.

**Comment by ThePhantom00** [comment]
[One.Piece.E1095.zip](https://github.com/PhosCity/Aegisub-Scripts/files/14864232/One.Piece.E1095.zip)

here's the file u can test it
it happens in some places not in whole project

**Comment by PhosCity** [comment]
I've pushed a fix. Update the script and reopen the issue if it is still not fixed for you.
